In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [6]:
#importing the data tables

df = pd.read_csv("Data Table.csv")
products = pd.read_csv("Products.csv")

In [7]:
df.info()
products.info()
#as we can see, no null values in any table

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440 entries, 0 to 439
Data columns (total 9 columns):
TransactionID          440 non-null object
Transaction            440 non-null object
CustomerID             440 non-null object
Mobile_number          440 non-null int64
Customer Name          440 non-null object
Age                    440 non-null int64
Billing Without GST    440 non-null int64
Billing With GST       440 non-null int64
Date                   440 non-null object
dtypes: int64(4), object(5)
memory usage: 31.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 5 columns):
Unnamed: 0       13 non-null int64
Product Name     13 non-null object
Costing Price    13 non-null float64
Selling Price    13 non-null int64
Profit           13 non-null float64
dtypes: float64(2), int64(2), object(1)
memory usage: 648.0+ bytes

In [8]:
#looking into the data
df

,TransactionID,Transaction,CustomerID,Mobile_number,Customer Name,Age,Billing Without GST,Billing With GST,Date
0,TI0001,"['Camera', 'SD-card', 'Camera-holder']",CUST023,7023711077,Safyr,28,53750,60200,1/1/2017
1,TI0002,"['Camera', 'Focus-lens', 'SD-card', 'Camera-ho...",CUST012,7023711088,Ballinamore,24,68750,77000,1/1/2017
2,TI0003,"['Camera', 'Auto-focus-mount-adapter', 'Tripod...",CUST034,7023711066,Sahib,59,70050,78456,1/1/2017
3,TI0004,"['Camera', 'Focus-lens', 'SD-card', 'Camera-ho...",CUST008,7023711092,Ballad,12,68750,77000,1/1/2017
4,TI0005,"['Camera', 'Camera-holder', 'Photographic-ligh...",CUST029,7023711071,Sagiv,30,56100,62832,1/1/2017
...,...,...,...,...,...,...,...,...,...
435,TI0436,"['Cover-Case', 'Screen-Protector']",CUST006,7023711094,Aaran,11,1400,1568,6/29/2017
436,TI0437,"['Power-Bank', 'SD-card', 'Sim']",CUST034,7023711066,Sahib,59,3900,4368,6/30/2017
437,TI0438,"['SD-card', 'Screen-Protector', 'Sim']",CUST021,7023711079,Safak,27,1700,1904,7/1/2017
438,TI0439,"['Mobile-phone', 'Sim']",CUST010,7023711090,Ballentine,23,45150,50568,7/2/2017
439,TI0440,"['Screen-Protector', 'Sim']",CUST016,7023711084,Balthazar,25,450,504,7/3/2017

In [9]:
df["CustomerID"].value_counts()

CUST038    17
CUST021    16
CUST007    16
CUST015    16
CUST031    15
CUST033    14
CUST037    14
CUST016    14
CUST032    13
CUST011    13
CUST039    13
CUST024    13
CUST005    12
CUST029    12
CUST019    12
CUST017    12
CUST025    12
CUST034    11
CUST001    11
CUST036    11
CUST040    11
CUST009    10
CUST012    10
CUST028    10
CUST027    10
CUST023    10
CUST022     9
CUST004     9
CUST002     9
CUST008     9
CUST010     8
CUST030     8
CUST014     8
CUST018     8
CUST020     8
CUST006     8
CUST003     8
CUST026     7
CUST013     7
CUST035     6
Name: CustomerID, dtype: int64

In [10]:
#as we can see above, for apriori algorithm their are many unwanted column in our data, so we will drop them
list1 = ["CustomerID", "Mobile_number", "Customer Name", "Age" ,"Billing Without GST", "Billing With GST", "Date"]
df_apriori = df.drop(list1,axis=1)

def Camera(row):
    row = row.split("'")
    if "Camera" in row:
        return 1
    else:
        return 0

def Mobile_phone(row):
    row = row.split("'")
    if "Mobile-phone" in row:
        return 1
    else:
        return 0
    
def Screen_Protector(row):
    row = row.split("'")
    if "Screen-Protector" in row:
        return 1
    else:
        return 0

def Sim(row):
    row = row.split("'")
    if "Sim" in row:
        return 1
    else:
        return 0
    
def Cover_Case(row):
    row = row.split("'")
    if "Cover-Case" in row:
        return 1
    else:
        return 0
    
def Earphones(row):
    row = row.split("'")
    if "Earphones" in row:
        return 1
    else:
        return 0
    
def Power_Bank(row):
    row = row.split("'")
    if "Power-Bank" in row:
        return 1
    else:
        return 0
    
def Focus_lens(row):
    row = row.split("'")
    if "Focus-lens" in row:
        return 1
    else:
        return 0
    
def SD_card(row):
    row = row.split("'")
    if "SD-card" in row:
        return 1
    else:
        return 0
    
def Camera_holder(row):
    row = row.split("'")
    if "Camera-holder" in row:
        return 1
    else:
        return 0
    
def Auto_focus_mount_adapter(row):
    row = row.split("'")
    if "Auto-focus-mount-adapter" in row:
        return 1
    else:
        return 0
    
def Tripod_stand(row):
    row = row.split("'")
    if "Tripod-stand" in row:
        return 1
    else:
        return 0
    
def Photographic_lighting(row):
    row = row.split("'")
    if "Photographic-lighting" in row:
        return 1
    else:
        return 0
    
    
    
df_apriori["Camera"] = df_apriori["Transaction"].apply(Camera)
df_apriori["Mobile Phone"] = df_apriori["Transaction"].apply(Mobile_phone)
df_apriori["Screen Protector"] = df_apriori["Transaction"].apply(Screen_Protector)
df_apriori["Sim"] = df_apriori["Transaction"].apply(Sim)
df_apriori["Cover Case"] = df_apriori["Transaction"].apply(Cover_Case)
df_apriori["Earphones"] = df_apriori["Transaction"].apply(Earphones)
df_apriori["Power Bank"] = df_apriori["Transaction"].apply(Power_Bank)
df_apriori["Focus lens"] = df_apriori["Transaction"].apply(Focus_lens)
df_apriori["SD-card"] = df_apriori["Transaction"].apply(SD_card)
df_apriori["Camera Holder"] = df_apriori["Transaction"].apply(Camera_holder)
df_apriori["Auto Focus Mount Adapter"] = df_apriori["Transaction"].apply(Auto_focus_mount_adapter)
df_apriori["Tripod Stand"] = df_apriori["Transaction"].apply(Tripod_stand)
df_apriori["Photographic Lighting"] = df_apriori["Transaction"].apply(Photographic_lighting)
    
    
    
#now we don't require the transaction attribute too, so we will drop it and make TransactionID as index of dataframe 
df_apriori.drop(["Transaction"],axis=1,inplace=True)
df_apriori.set_index("TransactionID",inplace = True)
df_apriori

,Camera,Mobile Phone,Screen Protector,Sim,Cover Case,Earphones,Power Bank,Focus lens,SD-card,Camera Holder,Auto Focus Mount Adapter,Tripod Stand,Photographic Lighting
TransactionID,,,,,,,,,,,,,
TI0001,1,0,0,0,0,0,0,0,1,1,0,0,0
TI0002,1,0,0,0,0,0,0,1,1,1,0,0,0
TI0003,1,0,0,0,0,0,0,0,0,0,1,1,1
TI0004,1,0,0,0,0,0,0,1,1,1,0,0,0
TI0005,1,0,0,0,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
TI0436,0,0,1,0,1,0,0,0,0,0,0,0,0
TI0437,0,0,0,1,0,0,1,0,1,0,0,0,0
TI0438,0,0,1,1,0,0,0,0,1,0,0,0,0
TI0439,0,1,0,1,0,0,0,0,0,0,0,0,0
TI0440,0,0,1,1,0,0,0,0,0,0,0,0,0

In [11]:
#products has nothing preprocessing part as it will be only used for fiding the profit per productand overall profit
products

,Unnamed: 0,Product Name,Costing Price,Selling Price,Profit
0,0,Mobile-phone,40500.0,45000,4500.0
1,1,Screen-Protector,90.0,300,210.0
2,2,Sim,120.0,150,30.0
3,3,Cover-Case,440.0,1100,660.0
4,4,Earphones,2000.0,2500,500.0
5,5,Power-Bank,1250.0,2500,1250.0
6,6,Camera,35000.0,50000,15000.0
7,7,Focus-lens,9600.0,15000,5400.0
8,8,SD-card,1187.5,1250,62.5
9,9,Camera-holder,1875.0,2500,625.0
10,10,Auto-focus-mount-adapter,12495.0,14700,2205.0
11,11,Tripod-stand,1172.5,1750,577.5
12,12,Photographic-lighting,2700.0,3600,900.0

In [12]:
#Training the model using apriori
my_frequent_itemsets = apriori(df_apriori , min_support = 0.1, use_colnames = True)
my_rules = association_rules(my_frequent_itemsets, metric='lift', min_threshold=1)
my_rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Camera),(Focus lens),0.361364,0.186364,0.125000,0.345912,1.856113,0.057655,1.243925
1,(Focus lens),(Camera),0.186364,0.361364,0.125000,0.670732,1.856113,0.057655,1.939562
2,(Camera),(SD-card),0.361364,0.477273,0.211364,0.584906,1.225517,0.038895,1.259298
3,(SD-card),(Camera),0.477273,0.361364,0.211364,0.442857,1.225517,0.038895,1.146270
4,(Camera),(Camera Holder),0.361364,0.302273,0.200000,0.553459,1.830993,0.090770,1.562516
5,(Camera Holder),(Camera),0.302273,0.361364,0.200000,0.661654,1.830993,0.090770,1.887525
6,(Mobile Phone),(Sim),0.265909,0.250000,0.111364,0.418803,1.675214,0.044886,1.290441
7,(Sim),(Mobile Phone),0.250000,0.265909,0.111364,0.445455,1.675214,0.044886,1.323770
8,(SD-card),(Focus lens),0.477273,0.186364,0.100000,0.209524,1.124274,0.011054,1.029299
9,(Focus lens),(SD-card),0.186364,0.477273,0.100000,0.536585,1.124274,0.011054,1.127990
10,(SD-card),(Camera Holder),0.477273,0.302273,0.170455,0.357143,1.181525,0.026188,1.085354
11,(Camera Holder),(SD-card),0.302273,0.477273,0.170455,0.563910,1.181525,0.026188,1.198668
12,"(Camera, SD-card)",(Camera Holder),0.211364,0.302273,0.111364,0.526882,1.743067,0.047474,1.474742
13,"(Camera, Camera Holder)",(SD-card),0.200000,0.477273,0.111364,0.556818,1.166667,0.015909,1.179487
14,"(SD-card, Camera Holder)",(Camera),0.170455,0.361364,0.111364,0.653333,1.807966,0.049768,1.842220
15,(Camera),"(SD-card, Camera Holder)",0.361364,0.170455,0.111364,0.308176,1.807966,0.049768,1.199070
16,(SD-card),"(Camera, Camera Holder)",0.477273,0.200000,0.111364,0.233333,1.166667,0.015909,1.043478
17,(Camera Holder),"(Camera, SD-card)",0.302273,0.211364,0.111364,0.368421,1.743067,0.047474,1.248674

In [16]:
my_rules[ (my_rules["lift"]>=1.5) & (my_rules["confidence"]>=0.5)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
1,(Focus lens),(Camera),0.186364,0.361364,0.125000,0.670732,1.856113,0.057655,1.939562
4,(Camera),(Camera Holder),0.361364,0.302273,0.200000,0.553459,1.830993,0.090770,1.562516
5,(Camera Holder),(Camera),0.302273,0.361364,0.200000,0.661654,1.830993,0.090770,1.887525
12,"(Camera, SD-card)",(Camera Holder),0.211364,0.302273,0.111364,0.526882,1.743067,0.047474,1.474742
14,"(SD-card, Camera Holder)",(Camera),0.170455,0.361364,0.111364,0.653333,1.807966,0.049768,1.842220

In [18]:
df_apriori[df_apriori["Camera"]==1]
#df_apriori[df_apriori["Camera Holder"]==1]

,Camera,Mobile Phone,Screen Protector,Sim,Cover Case,Earphones,Power Bank,Focus lens,SD-card,Camera Holder,Auto Focus Mount Adapter,Tripod Stand,Photographic Lighting
TransactionID,,,,,,,,,,,,,
TI0001,1,0,0,0,0,0,0,0,1,1,0,0,0
TI0002,1,0,0,0,0,0,0,1,1,1,0,0,0
TI0003,1,0,0,0,0,0,0,0,0,0,1,1,1
TI0004,1,0,0,0,0,0,0,1,1,1,0,0,0
TI0005,1,0,0,0,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
TI0216,1,0,0,0,0,0,0,0,0,1,1,0,0
TI0217,1,0,0,0,0,0,0,0,1,1,0,0,0
TI0218,1,0,0,0,0,0,0,1,1,0,0,0,0
TI0219,1,0,0,0,0,0,0,0,1,1,1,0,0
TI0220,1,0,0,0,0,0,0,0,0,1,0,0,0

In [19]:
#Now as we have find the frequent patterns, let's check the individual product
profit = []
templist = list(products["Product Name"])
templist1 = list(df_apriori.columns)
for i in range(7):
    profit.append(len(df_apriori[df_apriori[templist1[i+1]] == 1])*int(products.loc[products["Product Name"] == templist[i]]["Profit"]))
profit.append( len(df_apriori[df_apriori["Camera"] == 1])*int(products.loc[products["Product Name"] == "Camera"]["Profit"]))
for i in range(8,13):
    profit.append(len(df_apriori[df_apriori[templist1[i]] == 1])*int(products.loc[products["Product Name"] == templist[i]]["Profit"]))
    
#for i in products["Product Name"]:
#    if i == "Mobile-phone"
#    profit.append(len(df_apriori[df_apriori[i] == 1])*(products.loc[products["Product Name"] == i]["Profit"]))
products["Total Profit"] = profit
products.sort_values(by = ["Total Profit"])

,Unnamed: 0,Product Name,Costing Price,Selling Price,Profit,Total Profit
2,2,Sim,120.0,150,30.0,3300
8,8,SD-card,1187.5,1250,62.5,13020
1,1,Screen-Protector,90.0,300,210.0,17430
5,5,Power-Bank,1250.0,2500,1250.0,18750
11,11,Tripod-stand,1172.5,1750,577.5,19618
12,12,Photographic-lighting,2700.0,3600,900.0,26100
4,4,Earphones,2000.0,2500,500.0,28500
3,3,Cover-Case,440.0,1100,660.0,31680
9,9,Camera-holder,1875.0,2500,625.0,83125
10,10,Auto-focus-mount-adapter,12495.0,14700,2205.0,90405
0,0,Mobile-phone,40500.0,45000,4500.0,526500
6,6,Camera,35000.0,50000,15000.0,1230000
7,7,Focus-lens,9600.0,15000,5400.0,2385000

In [73]:
#as we can we got most of profit from selling the focus-lens, camera and mobile-phone, and other profit was good but
#with very low profit in Sim.

['Camera',
 'Mobile Phone',
 'Screen Protector',
 'Sim',
 'Cover Case',
 'Earphones',
 'Power Bank',
 'Focus lens',
 'SD-card',
 'Camera Holder',
 'Auto Focus Mount Adapter',
 'Tripod Stand',
 'Photographic Lighting']

In [3]:
temp = df["Transaction"][0]
temp

"['Camera', 'SD-card', 'Camera-holder']"

In [4]:
temp.split("'")

['[', 'Camera', ', ', 'SD-card', ', ', 'Camera-holder', ']']